function Hd = low_pass_for_envelope(Fc, N, Fs)
%LOW_PASS_FOR_ENVELOPE Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.3 and DSP System Toolbox 9.5.
% Generated on: 06-Jul-2018 09:33:50

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
% Fs = ;  % Sampling Frequency

% N  = ;  % Order
% Fc = ;  % Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass('N,F3dB', N, Fc, Fs);
Hd = design(h, 'butter');

% [EOF]
